name_jab = input("Enter your name: ")
age_jab = input("Enter your age: ")
course_jab = input("Enter your course: ")
university_jab = input("Enter your university: ")
print("\n----- STUDENT PROFILE -----")
print("Name:", name_jab)
print("Age:", age_jab)
print("Course:", course_jab)
print("University:", university_jab)
